hydra:
  run:
    dir: /workspaces/nigbms/data/poisson2d/small
  job:
    chdir: True

N_data: 1000

dataset:
  _target_: nigbms.data.OnlineDataset
  constructor: 
    _target_: examples.poisson2d.task.Poisson2DTaskConstructor
    # TODO: Setting task.Poisson2DTaskConstructor gives an error when loading saved .pkl files. This should be fixed.
  distribution:
    _target_: nigbms.tasks.TaskDistribution
    task_params_class:
      _target_: hydra.utils.get_class
      path: examples.poisson2d.task.Poisson2DParams
    distributions:
      Tmax:
        _target_: nigbms.utils.distributions.NumpyUniform
        shape: null
        lb: 0
        ub: 100
      alpha: ${.Tmax}

      Nx:
        _target_: nigbms.utils.distributions.NumpyConstant
        shape: null
        value: 10
      Ny: ${.Nx}
      rtol:
        _target_: nigbms.utils.distributions.NumpyConstant
        shape: null
        value: 1.0e-3
      maxiter:
        _target_: nigbms.utils.distributions.NumpyConstant
        shape: null
        value: 1000