hydra:
  run:
    dir: data/raw/poisson2d/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True

N_data: 1000

dataset:
  _target_: nigbms.modules.data.OnlineDataset
  task_params_type: 
    _target_: hydra.utils.get_class
    path: nigbms.data.generate_poisson2d.Poisson2DParams
  task_constructor: 
    _target_: hydra.utils.get_method
    path: nigbms.data.generate_poisson2d.construct_petsc_poisson2d_task
  distributions:
    coef:
      _target_: nigbms.utils.distributions.NumpyNormal
      shape: [2,]
      mean: 0
      std: 1
    N:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      value: 10
    degree:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      value: 1
    rtol:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      value: 1.0e-6
    maxiter:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      value: 1000