defaults:
  - common
  - meta_solver: constant_meta_solver_default
  - solver: testfunction_solver_default
  - surrogate: testfunction_surrogate_default
  - constructor: constructor_testfunction_default
  - wrapper: wrapped_solver_default
  - _self_

wandb:
  mode: disabled

problem:
  test_function: sphere
  dim: 128
  num_samples: 100
  num_iter: 1000
  initial_range:
    - -1
    - 1

meta_solver:
  model:
    shape:
      - ${problem.num_samples}
      - ${problem.dim}
    range: ${problem.initial_range}

solver:
  params_learn: 
    x:
      - ${problem.dim}
      - 1

surrogate:
  params_learn: ${solver.params_learn}
  features: ${surrogate.params_learn}
  model:
    # _target_: nigbms.modules.models.CNN1D
    _target_: nigbms.modules.models.MLPSkip
    n_units: 256
    n_layers: 2
    kernel_size: 1
    base_channels: 64
    skip: True
    hidden_activation:
      _target_: torch.nn.GELU
    

constructor:
  params:
    x:
      codec: 
        _target_: nigbms.modules.constructors.IdentityCodec
        param_dim: ${problem.dim}
        latent_dim: ${problem.dim}
      shape: 
        - ${problem.dim}

wrapper:
  hparams:
    clip: null
    grad_type: cv_fwd
    jvp_type: forwardAD
    eps: 1.0e-8
    Nv: 1
    v_scale: 1.0
    v_dist: rademacher
    additional_steps: 5

opt:
  _target_: torch.optim.SGD
  lr: 0.01

clip: null
device: cuda

